### ISSUE TITLE
Does not play well with Telescope

### ISSUE THREAD

**Issue by nkrkv** [nkrkv/nvim-treesitter-rescript#3]
For some reason [Telescope](https://github.com/nvim-telescope/telescope.nvim) does not recognize ReScript files correctly:

- Run `:Telescope treesitter` and nothing happens. No error, no Telescope window, nothing
- Run `:Telescope find_files` and hover a `.res` file. In the preview window, it does not get highlighted. To be more precise, some rare fragments are highlighted (improperly) but that's it.

Perhaps Telescope tries to process ReScript with another parser.

For JavaScript, for example, it works fine.

**Comment by aspeddro** [comment]
Syntax highlight is an issue with upstream plenary (telescope dependencie). https://github.com/nvim-lua/plenary.nvim/pull/318

![image](https://user-images.githubusercontent.com/16160544/152882723-da9946fc-1c2c-47a4-bb77-b0bcaa365176.png)

**Comment by nkrkv** [comment]
Thank you for nailing it down. In the PR you’ve created, it would be nice to have a mapping for `resi` in addition to `res`

**Comment by aspeddro** [comment]
https://github.com/nvim-lua/plenary.nvim/pull/318 was merged

**Comment by nkrkv** [comment]
Oh, it works indeed!
