### ISSUE TITLE
Does not work with iswap.nvim

### ISSUE THREAD

**Issue by kiuKisas** [nkrkv/nvim-treesitter-rescript#6]
[iswap.nvim](https://github.com/mizlan/iswap.nvim) use tree-sitter to easily swap parameters, list,...
When I try with a `res` file, I got this error: `Cannot query this filetype`
EDIT: probably linked to https://github.com/nkrkv/nvim-treesitter-rescript/pull/5

**Comment by b0o** [comment]
It looks like that plugin could be supported with a `queries/rescript/iswap-list.scm` file with a simple query, should be pretty easy.

**Comment by nkrkv** [comment]
Looks resolved. Feel free to re-open if I miss something. Thank you!
